### ISSUE TITLE
What about using SysV ABI instead of MS ABI?

### ISSUE THREAD

**Issue by lucsm00** [ExoVerse/osdev-UEFI-series#2]
The documentation of GCC states that:

> The default is to use the Microsoft ABI when targeting Microsoft Windows and the SysV ABI on all other systems.

That said, since we are targeting a freestanding environment, wouldn't it be better to use the recommended calling convention by setting `-mabi=sysv`?

I search about it on the specifications and it seems like it does not define a recommended calling convention. This message is just a discussion thread and depending on the talk I can adapt the building scripts.

**Comment by ExoVerse** [comment]
sysv is linux specific. The reason we use -mabi=ms is because we are on a windows environment. And the UEFI is default for the windows format, which is why FAT32 is the format used for the partition. Bottom line, there is no reason to use anything related to linux, in a windows or EFI environment.
